package com.linkpoint.protocol.llsd

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Cross-implementation conformance test against the canonical
 * `python-llsd` library (v1.2.4, MIT, maintained by Linden Lab).
 *
 * The fixture directory `src/test/resources/llsd-conformance/vectors/`
 * is generated by `generate_vectors.py`, which writes pairs of
 * `value.xml` + `value.bin` for ~30 LLSD trees covering scalar types,
 * container shapes, edge cases (empty/long strings, INT_MIN, every byte
 * value in a binary blob), and realistic SL response shapes (seed cap
 * reply, JSEP offer payload, ICE trickle batch, buddy-list entry).
 *
 * For each fixture:
 *   1. Parse the XML form via `LLSDParser.parseXML` → `xmlTree`.
 *   2. Parse the binary form via `LLSDParser.parseBinary` → `binTree`.
 *   3. Assert `xmlTree == binTree`. If they disagree, one of our
 *      parsers is wrong vs the canonical impl.
 *   4. Round-trip: re-emit `xmlTree.toBinary()` and `xmlTree.toXML()`,
 *      re-parse them, and assert equality with the original. This
 *      catches encoder bugs that don't show up on the read path alone.
 *
 * The bar is *not* byte-equality with python-llsd's output — XML
 * whitespace and binary length-prefix encoding can differ harmlessly
 * between implementations. The bar is *semantic equality*: every tree
 * python-llsd emits must round-trip cleanly through our codec.
 *
 * If a vector fails, the failure message tells you which fixture and
 * which form (xml vs bin vs round-trip) — so a single broken codec
 * branch produces a focused regression rather than a generic "all the
 * tests fail" cascade.
 */
class LLSDConformanceTest {

    private val vectorsDir: File by lazy {
        // Resources are on the classpath under `llsd-conformance/vectors/`.
        // We resolve via the test's class loader so this works whether
        // the build system uses Gradle's resource layout or a manual
        // classpath. Fall back to the source tree for direct IDE runs.
        val res = javaClass.classLoader.getResource("llsd-conformance/vectors")
        if (res != null) {
            File(res.toURI())
        } else {
            File("src/test/resources/llsd-conformance/vectors")
        }
    }

    @Test
    fun `every fixture round-trips cleanly through both XML and binary codecs`() {
        val dir = vectorsDir
        if (!dir.isDirectory) {
            fail("Conformance vectors not found at $dir. Run generate_vectors.py.")
            return
        }

        val fixtures = dir.listFiles { f -> f.isDirectory }?.sortedBy { it.name }
            ?: error("No fixture subdirectories under $dir")
        assertNotNull("Expected fixture subdirectories under $dir", fixtures)
        check(fixtures.isNotEmpty()) { "No fixture subdirectories found under $dir" }

        val failures = mutableListOf<String>()
        for (fix in fixtures) {
            try {
                runFixture(fix)
            } catch (e: AssertionError) {
                failures += "${fix.name}: ${e.message}"
            } catch (e: Exception) {
                failures += "${fix.name}: ${e.javaClass.simpleName}: ${e.message}"
            }
        }

        if (failures.isNotEmpty()) {
            fail(
                "LLSD conformance failures (${failures.size}/${fixtures.size}):\n" +
                    failures.joinToString("\n") { "  - $it" }
            )
        }
    }

    private fun runFixture(dir: File) {
        val xmlBytes = File(dir, "value.xml").readBytes()
        val binBytes = File(dir, "value.bin").readBytes()
        val xmlString = String(xmlBytes, Charsets.UTF_8)

        // 1. Parse both forms.
        val fromXml = LLSDParser.parseXML(xmlString)
        val fromBin = LLSDParser.parseBinary(binBytes)

        // 2. The two trees must agree. Mismatches mean one parser has a
        //    bug that python-llsd's emitter doesn't trip itself up on.
        //    LLSDValue subclasses are data classes, so structural ==
        //    works for nested maps/arrays and scalar UUIDs / dates /
        //    binary content (LLSDBinary overrides equals).
        assertEquals("xml ↔ bin tree mismatch", normalise(fromXml), normalise(fromBin))

        // 3. Re-emit each form and re-parse. This catches encoder bugs.
        val reXml = LLSDXmlUtils.wrap(fromXml)
        val reBin = fromXml.toBinary()
        val reFromXml = LLSDParser.parseXML(reXml)
        val reFromBin = LLSDParser.parseBinary(reBin)

        assertEquals("xml round-trip changed the tree", normalise(fromXml), normalise(reFromXml))
        assertEquals("bin round-trip changed the tree", normalise(fromXml), normalise(reFromBin))
    }

    /**
     * python-llsd serialises `null` as the LLSD `<undef/>` marker, which
     * Linkpoint's XML parser models as `LLSDUndefined` (the standard
     * representation). The binary parser does the same. No
     * normalisation needed in the common case — but if a future fixture
     * exercises a case where the two parsers disagree on a *type*
     * (e.g. an empty `<integer/>` element vs. `<integer>0</integer>`),
     * fold the disagreement here rather than masking the bug with
     * `assertEquals` tolerances.
     */
    private fun normalise(value: LLSDValue): LLSDValue = value
}
