package com.linkpoint.linden.llmessage

object MessageTemplateCatalog {
    private val _templates: MutableMap<String, MessageTemplate> = linkedMapOf()

    private fun add(
        name: String,
        frequency: Frequency = Frequency.LOW,
        messageNumber: UInt = 0u,
        trust: Trust = Trust.NOTRUST,
        encoding: Encoding = Encoding.ZEROCODED,
        deprecation: Deprecation = Deprecation.NOT_DEPRECATED,
    ) {
        _templates[name] = MessageTemplate(name, frequency, messageNumber, trust, encoding, deprecation)
    }

    init {
        // ── Active messages ───────────────────────────────────────────────
        // Frequency and messageNumber are placeholders (0u / LOW); exact
        // values are populated when message_template.msg parsing is added.
        add("AbortXfer")
        add("AcceptCallingCard")
        add("AcceptFriendship")
        add("ActivateGestures")
        add("ActivateGroup")
        add("AddCircuitCode")
        add("AgentAlertMessage")
        add("AgentAnimation")
        add("AgentCachedTexture")
        add("AgentCachedTextureResponse")
        add("AgentDataUpdate")
        add("AgentDataUpdateRequest")
        add("AgentFOV")
        add("AgentHeightWidth")
        add("AgentIsNowWearing")
        add("AgentMovementComplete")
        add("AgentPause")
        add("AgentQuitCopy")
        add("AgentRequestSit")
        add("AgentResume")
        add("AgentSetAppearance")
        add("AgentSit")
        add("AgentThrottle")
        add("AgentUpdate")
        add("AgentWearablesRequest")
        add("AgentWearablesUpdate")
        add("AlertMessage")
        add("AssetUploadComplete")
        add("AssetUploadRequest")
        add("AtomicPassObject")
        add("AttachedSound")
        add("AttachedSoundGainChange")
        add("AvatarAnimation")
        add("AvatarAppearance")
        add("AvatarClassifiedReply")
        add("AvatarGroupsReply")
        add("AvatarInterestsReply")
        add("AvatarInterestsUpdate")
        add("AvatarNotesReply")
        add("AvatarNotesUpdate")
        add("AvatarPickerReply")
        add("AvatarPickerRequest")
        add("AvatarPickerRequestBackend")
        add("AvatarPicksReply")
        add("AvatarPropertiesReply")
        add("AvatarPropertiesRequest")
        add("AvatarPropertiesRequestBackend")
        add("AvatarPropertiesUpdate")
        add("AvatarSitResponse")
        add("AvatarTextureUpdate")
        add("BulkUpdateInventory")
        add("BuyObjectInventory")
        add("CameraConstraint")
        add("CancelAuction")
        add("ChangeInventoryItemFlags")
        add("ChangeUserRights")
        add("ChatFromSimulator")
        add("ChatFromViewer")
        add("ChatPass")
        add("CheckParcelAuctions")
        add("CheckParcelSales")
        add("ChildAgentAlive")
        add("ChildAgentDying")
        add("ChildAgentPositionUpdate")
        add("ChildAgentUnknown")
        add("ChildAgentUpdate")
        add("ClassifiedDelete")
        add("ClassifiedGodDelete")
        add("ClassifiedInfoReply")
        add("ClassifiedInfoRequest")
        add("ClassifiedInfoUpdate")
        add("ClearFollowCamProperties")
        add("CoarseLocationUpdate")
        add("CompleteAgentMovement")
        add("CompleteAuction")
        add("CompletePingCheck")
        add("ConfirmAuctionStart")
        add("ConfirmEnableSimulator")
        add("ConfirmXferPacket")
        add("CopyInventoryItem")
        add("CreateGroupReply")
        add("CreateGroupRequest")
        add("CreateInventoryFolder")
        add("CreateInventoryItem")
        add("CreateLandmarkForEvent")
        add("CreateNewOutfitAttachments")
        add("CreateTrustedCircuit")
        add("CrossedRegion")
        add("DataHomeLocationReply")
        add("DataHomeLocationRequest")
        add("DataServerLogout")
        add("DeRezAck")
        add("DeRezObject")
        add("DeactivateGestures")
        add("DeclineCallingCard")
        add("DeclineFriendship")
        add("DenyTrustedCircuit")
        add("DerezContainer")
        add("DetachAttachmentIntoInv")
        add("DirClassifiedQuery")
        add("DirClassifiedQueryBackend")
        add("DirClassifiedReply")
        add("DirEventsReply")
        add("DirFindQuery")
        add("DirFindQueryBackend")
        add("DirGroupsReply")
        add("DirLandQuery")
        add("DirLandQueryBackend")
        add("DirPeopleReply")
        add("DirPlacesQuery")
        add("DirPlacesQueryBackend")
        add("DirPlacesReply")
        add("DisableSimulator")
        add("EconomyData")
        add("EconomyDataRequest")
        add("EdgeDataPacket")
        add("EjectGroupMemberReply")
        add("EjectGroupMemberRequest")
        add("EjectUser")
        add("EmailMessageReply")
        add("EmailMessageRequest")
        add("EnableSimulator")
        add("Error")
        add("EstateCovenantReply")
        add("EstateCovenantRequest")
        add("EstateOwnerMessage")
        add("EventGodDelete")
        add("EventInfoReply")
        add("EventInfoRequest")
        add("EventLocationReply")
        add("EventLocationRequest")
        add("EventNotificationAddRequest")
        add("EventNotificationRemoveRequest")
        add("FeatureDisabled")
        add("FetchInventory")
        add("FetchInventoryDescendents")
        add("FetchInventoryReply")
        add("FindAgent")
        add("ForceObjectSelect")
        add("ForceScriptControlRelease")
        add("FormFriendship")
        add("FreezeUser")
        add("GenericMessage")
        add("GetScriptRunning")
        add("GodKickUser")
        add("GodUpdateRegionInfo")
        add("GodlikeMessage")
        add("GrantGodlikePowers")
        add("GrantUserRights")
        add("GroupAccountDetailsReply")
        add("GroupAccountDetailsRequest")
        add("GroupAccountSummaryReply")
        add("GroupAccountSummaryRequest")
        add("GroupAccountTransactionsReply")
        add("GroupAccountTransactionsRequest")
        add("GroupActiveProposalItemReply")
        add("GroupActiveProposalsRequest")
        add("GroupDataUpdate")
        add("GroupMembersReply")
        add("GroupMembersRequest")
        add("GroupNoticeAdd")
        add("GroupNoticeRequest")
        add("GroupNoticesListReply")
        add("GroupNoticesListRequest")
        add("GroupProfileReply")
        add("GroupProfileRequest")
        add("GroupRoleChanges")
        add("GroupRoleDataReply")
        add("GroupRoleDataRequest")
        add("GroupRoleMembersReply")
        add("GroupRoleMembersRequest")
        add("GroupRoleUpdate")
        add("GroupTitleUpdate")
        add("GroupTitlesReply")
        add("GroupTitlesRequest")
        add("GroupVoteHistoryItemReply")
        add("GroupVoteHistoryRequest")
        add("HealthMessage")
        add("ImageData")
        add("ImageNotInDatabase")
        add("ImagePacket")
        add("ImprovedInstantMessage")
        add("ImprovedTerseObjectUpdate")
        add("InitiateDownload")
        add("InternalScriptMail")
        add("InventoryAssetResponse")
        add("InventoryDescendents")
        add("InviteGroupRequest")
        add("InviteGroupResponse")
        add("JoinGroupReply")
        add("JoinGroupRequest")
        add("KickUser")
        add("KickUserAck")
        add("KillChildAgents")
        add("KillObject")
        add("LandStatRequest")
        add("LayerData")
        add("LeaveGroupReply")
        add("LeaveGroupRequest")
        add("LinkInventoryItem")
        add("LiveHelpGroupReply")
        add("LiveHelpGroupRequest")
        add("LoadURL")
        add("LogDwellTime")
        add("LogFailedMoneyTransaction")
        add("LogParcelChanges")
        add("LogTextMessage")
        add("LogoutReply")
        add("LogoutRequest")
        add("MapBlockReply")
        add("MapBlockRequest")
        add("MapItemReply")
        add("MapItemRequest")
        add("MapLayerReply")
        add("MapLayerRequest")
        add("MapNameRequest")
        add("MeanCollisionAlert")
        add("MergeParcel")
        add("ModifyLand")
        add("MoneyBalanceReply")
        add("MoneyBalanceRequest")
        add("MoneyTransferBackend")
        add("MoneyTransferRequest")
        add("MoveInventoryFolder")
        add("MoveInventoryItem")
        add("MoveTaskInventory")
        add("MultipleObjectUpdate")
        add("MuteListRequest")
        add("MuteListUpdate")
        add("NameValuePair")
        add("NearestLandingRegionReply")
        add("NearestLandingRegionRequest")
        add("NearestLandingRegionUpdated")
        add("NeighborList")
        add("NetTest")
        add("ObjectAdd")
        add("ObjectAttach")
        add("ObjectBuy")
        add("ObjectCategory")
        add("ObjectClickAction")
        add("ObjectDeGrab")
        add("ObjectDelete")
        add("ObjectDelink")
        add("ObjectDeselect")
        add("ObjectDescription")
        add("ObjectDetach")
        add("ObjectDrop")
        add("ObjectDuplicate")
        add("ObjectDuplicateOnRay")
        add("ObjectExportSelected")
        add("ObjectExtraParams")
        add("ObjectFlagUpdate")
        add("ObjectGrab")
        add("ObjectGrabUpdate")
        add("ObjectGroup")
        add("ObjectImage")
        add("ObjectIncludeInSearch")
        add("ObjectLink")
        add("ObjectMaterial")
        add("ObjectName")
        add("ObjectOwner")
        add("ObjectPermissions")
        add("ObjectProperties")
        add("ObjectPropertiesFamily")
        add("ObjectRotation")
        add("ObjectSaleInfo")
        add("ObjectSelect")
        add("ObjectShape")
        add("ObjectSpinStart")
        add("ObjectSpinStop")
        add("ObjectSpinUpdate")
        add("ObjectUpdate")
        add("ObjectUpdateCached")
        add("ObjectUpdateCompressed")
        add("OfferCallingCard")
        add("OfflineNotification")
        add("OnlineNotification")
        add("ParcelAccessListReply")
        add("ParcelAccessListRequest")
        add("ParcelAccessListUpdate")
        add("ParcelAuctions")
        add("ParcelBuy")
        add("ParcelBuyPass")
        add("ParcelClaim")
        add("ParcelDeedToGroup")
        add("ParcelDisableObjects")
        add("ParcelDivide")
        add("ParcelDwellReply")
        add("ParcelDwellRequest")
        add("ParcelGodForceOwner")
        add("ParcelGodMarkAsContent")
        add("ParcelInfoReply")
        add("ParcelInfoRequest")
        add("ParcelJoin")
        add("ParcelMediaCommandMessage")
        add("ParcelMediaUpdate")
        add("ParcelObjectOwnersRequest")
        add("ParcelOverlay")
        add("ParcelProperties")
        add("ParcelPropertiesRequest")
        add("ParcelPropertiesRequestByID")
        add("ParcelPropertiesUpdate")
        add("ParcelReclaim")
        add("ParcelRelease")
        add("ParcelRename")
        add("ParcelReturnObjects")
        add("ParcelSales")
        add("ParcelSelectObjects")
        add("ParcelSetOtherCleanTime")
        add("PayPriceReply")
        add("PickDelete")
        add("PickGodDelete")
        add("PickInfoReply")
        add("PickInfoUpdate")
        add("PlacesQuery")
        add("PreloadSound")
        add("PurgeInventoryDescendents")
        add("RebakeAvatarTextures")
        add("Redo")
        add("RegionHandleRequest")
        add("RegionHandshake")
        add("RegionHandshakeReply")
        add("RegionIDAndHandleReply")
        add("RegionInfo")
        add("RegionPresenceRequestByHandle")
        add("RegionPresenceRequestByRegionID")
        add("RegionPresenceResponse")
        add("RemoveAttachment")
        add("RemoveInventoryFolder")
        add("RemoveInventoryItem")
        add("RemoveInventoryObjects")
        add("RemoveMuteListEntry")
        add("RemoveNameValuePair")
        add("RemoveParcel")
        add("RemoveTaskInventory")
        add("ReplyTaskInventory")
        add("ReportAutosaveCrash")
        add("RequestGodlikePowers")
        add("RequestImage")
        add("RequestInventoryAsset")
        add("RequestMultipleObjects")
        add("RequestObjectPropertiesFamily")
        add("RequestParcelTransfer")
        add("RequestPayPrice")
        add("RequestRegionInfo")
        add("RequestTaskInventory")
        add("RequestTrustedCircuit")
        add("RequestXfer")
        add("RetrieveInstantMessages")
        add("RevokePermissions")
        add("RezMultipleAttachmentsFromInv")
        add("RezObject")
        add("RezObjectFromNotecard")
        add("RezScript")
        add("RezSingleAttachmentFromInv")
        add("RoutedMoneyBalanceReply")
        add("RpcChannelReply")
        add("RpcChannelRequest")
        add("RpcScriptReplyInbound")
        add("RpcScriptRequestInbound")
        add("SaveAssetIntoInventory")
        add("ScriptAnswerYes")
        add("ScriptControlChange")
        add("ScriptDataReply")
        add("ScriptDataRequest")
        add("ScriptDialog")
        add("ScriptDialogReply")
        add("ScriptMailRegistration")
        add("ScriptQuestion")
        add("ScriptReset")
        add("ScriptSensorReply")
        add("ScriptSensorRequest")
        add("ScriptTeleportRequest")
        add("SendPostcard")
        add("SendXferPacket")
        add("SetAlwaysRun")
        add("SetCPURatio")
        add("SetFollowCamProperties")
        add("SetGroupAcceptNotices")
        add("SetGroupContribution")
        add("SetScriptRunning")
        add("SetSimPresenceInDatabase")
        add("SetSimStatusInDatabase")
        add("SetStartLocation")
        add("SetStartLocationRequest")
        add("SimCrashed")
        add("SimStats")
        add("SimStatus")
        add("SimWideDeletes")
        add("SimulatorLoad")
        add("SimulatorMapUpdate")
        add("SimulatorPresentAtLocation")
        add("SimulatorReady")
        add("SimulatorSetMap")
        add("SimulatorShutdownRequest")
        add("SimulatorViewerTimeMessage")
        add("SoundTrigger")
        add("StartAuction")
        add("StartLure")
        add("StartPingCheck")
        add("StateSave")
        add("SubscribeLoad")
        add("SystemKickUser")
        add("SystemMessage")
        add("TallyVotes")
        add("TelehubInfo")
        add("TeleportCancel")
        add("TeleportFailed")
        add("TeleportFinish")
        add("TeleportLandingStatusChanged")
        add("TeleportLandmarkRequest")
        add("TeleportLocal")
        add("TeleportLocationRequest")
        add("TeleportLureRequest")
        add("TeleportProgress")
        add("TeleportRequest")
        add("TeleportStart")
        add("TerminateFriendship")
        add("TestMessage")
        add("TrackAgent")
        add("TransferAbort")
        add("TransferInfo")
        add("TransferInventory")
        add("TransferInventoryAck")
        add("TransferPacket")
        add("TransferRequest")
        add("UUIDGroupNameReply")
        add("UUIDGroupNameRequest")
        add("UUIDNameReply")
        add("UUIDNameRequest")
        add("Undo")
        add("UndoLand")
        add("UnsubscribeLoad")
        add("UpdateAttachment")
        add("UpdateCreateInventoryItem")
        add("UpdateGroupInfo")
        add("UpdateInventoryFolder")
        add("UpdateInventoryItem")
        add("UpdateMuteListEntry")
        add("UpdateParcel")
        add("UpdateSimulator")
        add("UpdateTaskInventory")
        add("UpdateUserInfo")
        add("UseCachedMuteList")
        add("UseCircuitCode")
        add("UserInfoReply")
        add("UserInfoRequest")
        add("UserReport")
        add("UserReportInternal")
        add("VelocityInterpolateOff")
        add("VelocityInterpolateOn")
        add("ViewerEffect")
        add("ViewerFrozenMessage")
        add("ViewerStartAuction")

        // ── Deprecated messages ───────────────────────────────────────────
        add("AgentDropGroup",                  deprecation = Deprecation.DEPRECATED)
        add("AgentGroupDataUpdate",            deprecation = Deprecation.DEPRECATED)
        add("CopyInventoryFromNotecard",       deprecation = Deprecation.DEPRECATED)
        add("DirLandReply",                    deprecation = Deprecation.DEPRECATED)
        add("DirPopularQuery",                 deprecation = Deprecation.DEPRECATED)
        add("DirPopularQueryBackend",          deprecation = Deprecation.DEPRECATED)
        add("DirPopularReply",                 deprecation = Deprecation.DEPRECATED)
        add("GroupProposalBallot",             deprecation = Deprecation.DEPRECATED)
        add("LandStatReply",                   deprecation = Deprecation.DEPRECATED)
        add("ObjectPosition",                  deprecation = Deprecation.DEPRECATED)
        add("ObjectScale",                     deprecation = Deprecation.DEPRECATED)
        add("ParcelObjectOwnersReply",         deprecation = Deprecation.DEPRECATED)
        add("PlacesReply",                     deprecation = Deprecation.DEPRECATED)
        add("RezRestoreToWorld",               deprecation = Deprecation.DEPRECATED)
        add("RpcScriptRequestInboundForward",  deprecation = Deprecation.DEPRECATED)
        add("ScriptRunningReply",              deprecation = Deprecation.DEPRECATED)
        add("StartGroupProposal",              deprecation = Deprecation.DEPRECATED)
        add("ViewerStats",                     deprecation = Deprecation.DEPRECATED)
    }

    operator fun get(name: String): MessageTemplate? = _templates[name]

    fun contains(name: String): Boolean = name in _templates

    val size: Int get() = _templates.size

    val allNames: Set<String>
        get() = _templates.keys.toSet()

    val activeNames: Set<String>
        get() = _templates.values
            .filter { it.deprecation == Deprecation.NOT_DEPRECATED }
            .map { it.name }
            .toSet()

    val deprecatedNames: Set<String>
        get() = _templates.values
            .filter { it.deprecation != Deprecation.NOT_DEPRECATED }
            .map { it.name }
            .toSet()
}
